AWSTemplateFormatVersion: 2010-09-09
Resources:
  ExoBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: std21108v001
  SsmARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['', [/test/arn, /s3/bucket-name]]
      Type: String
      Value: !GetAtt ExoBucket.Arn
  SsmName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['', [/test/name, /s3/bucket-name]]
      Type: String
      Value: !Ref ExoBucket